Repository wonderium/content, pull requests merged in 2024-09, with the labels that each got.

#4 Updates cards: css/pseudo-class, css/color-property
  css/color-property/data.json
  css/pseudo-class/data.json
Labels: Improvements, CSS

#5 Creates PR templates
  .github/PULL_REQUEST_TEMPLATE/edit_cards_pr_template.md
  .github/PULL_REQUEST_TEMPLATE/new_cards_pr_template.md
Labels: Quality

#8 Updates PR templates
  .github/PULL_REQUEST_TEMPLATE/edit_cards_pr_template.md
  .github/PULL_REQUEST_TEMPLATE/new_cards_pr_template.md
  .github/pull_request_template.md
Labels: Quality

#9 Creates cards in `CSS` level
  css/config.json
  css/moz-vendor-prefix/data.json
  css/ms-vendor-prefix/data.json
  css/webkit-vendor-prefix/data.json
Labels: CSS

#7 Creates the card: `js/return`
  js/config.json
  js/return/data.json
Labels: JavaScript

#11 Creates cards in `JavaScript` level
  js/config.json
  js/dom/data.json
  js/shadow-dom/data.json
Labels: Improvements, JavaScript

#13 Updates levels' config files
  .github/workflows/modify-content.yml
  a11y/config.json
  algorithms/config.json
  config.json
  css/config.json
  engineering/config.json
  html/config.json
  js/config.json
  react/config.json
  ts/config.json
  web/config.json
  work/config.json
Labels: Quality

#12 Updates cards: `js/dom`, `css/hex-color`
  css/hex-color/data.json
  js/dom/data.json
Labels: Improvements, CSS, JavaScript

#15 Updates cards in `HTML`, `JavaScript` levels
  html/accesskey/data.json
  html/attribute/data.json
  html/b/data.json
  html/comments/data.json
  js/intl-locale/data.json
Labels: HTML, JavaScript
